<project name="proxy" default="build">
  <property name="bin" location="bin" />

  <path id="main-classpath">
    <fileset dir="lib" includes="*.jar" />
    <path location="${bin}/production/proxy" />
  </path>

  <path id="test-classpath">
    <path location="lib/hamcrest-core-1.3.jar" />
    <path location="lib/junit-4.13.2.jar" />
    <path location="${bin}/test/proxy" />
  </path>

  <!-- prod -->
  <available file="/usr/local/bin/protoc" type="file" property="protoc" value="/usr/local/bin/protoc" />
  <available file="/usr/bin/protoc" type="file" property="protoc" value="/usr/bin/protoc" />

  <target name="build_proto">
    <exec executable="${protoc}">
      <arg value="--java_out=src/main/java"/>
      <arg value="src/main/proto/deagan.proto"/>
    </exec>
  </target>

  <target name="build" depends="build_proto">
    <mkdir dir="${bin}" />
    <javac srcdir="src/main/java" includes="**" destdir="${bin}/production/proxy" includeantruntime="false" debug="true" source="21" >
      <compilerarg value="--enable-preview" />
      <classpath>
        <path refid="main-classpath"/>
      </classpath>
    </javac>
  </target>

  <target name="test" depends="build">
    <mkdir dir="${bin}" />
    <javac srcdir="src/main/javatests" includes="**" destdir="${bin}/test/proxy" includeantruntime="false" debug="true" >
      <classpath>
        <path refid="main-classpath"/>
        <path refid="test-classpath"/>
      </classpath>
    </javac>
    <junit printsummary="on" haltonfailure="yes" fork="true">
      <formatter type="plain" usefile="false" />
      <classpath>
        <path refid="main-classpath"/>
        <path refid="test-classpath"/>
      </classpath>
      <batchtest>
        <fileset dir="${bin}/test/proxy" includes="**/*.class" />
      </batchtest>
    </junit>
  </target>

  <target name="clean">
    <delete dir="bin" />
  </target>

  <target name="run" depends="build">
    <java classname="org.spcgreenville.deagan.Proxy" fork="true">
      <sysproperty key="java.util.logging.config.file" value="props/local.logging.properties"/>
      <classpath>
        <path refid="main-classpath"/>
      </classpath>
    </java>
  </target>
</project>
