// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/deagan.proto

package org.spcgreenville.deagan;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeaganRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.spcgreenville.deagan.DeaganRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return Whether the heartbeat field is set.
     */
    boolean hasHeartbeat();
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return The heartbeat.
     */
    boolean getHeartbeat();

    /**
     * <code>optional int32 relay_number = 2;</code>
     * @return Whether the relayNumber field is set.
     */
    boolean hasRelayNumber();
    /**
     * <code>optional int32 relay_number = 2;</code>
     * @return The relayNumber.
     */
    int getRelayNumber();

    /**
     * <code>optional bool latch = 3;</code>
     * @return Whether the latch field is set.
     */
    boolean hasLatch();
    /**
     * <code>optional bool latch = 3;</code>
     * @return The latch.
     */
    boolean getLatch();

    /**
     * <code>optional bool chime = 4;</code>
     * @return Whether the chime field is set.
     */
    boolean hasChime();
    /**
     * <code>optional bool chime = 4;</code>
     * @return The chime.
     */
    boolean getChime();
  }
  /**
   * Protobuf type {@code org.spcgreenville.deagan.DeaganRequest}
   */
  public static final class DeaganRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.spcgreenville.deagan.DeaganRequest)
      DeaganRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeaganRequest.newBuilder() to construct.
    private DeaganRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeaganRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeaganRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeaganRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              heartbeat_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              relayNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              latch_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              chime_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.spcgreenville.deagan.Proto.DeaganRequest.class, org.spcgreenville.deagan.Proto.DeaganRequest.Builder.class);
    }

    private int bitField0_;
    public static final int HEARTBEAT_FIELD_NUMBER = 1;
    private boolean heartbeat_;
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public boolean getHeartbeat() {
      return heartbeat_;
    }

    public static final int RELAY_NUMBER_FIELD_NUMBER = 2;
    private int relayNumber_;
    /**
     * <code>optional int32 relay_number = 2;</code>
     * @return Whether the relayNumber field is set.
     */
    @java.lang.Override
    public boolean hasRelayNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 relay_number = 2;</code>
     * @return The relayNumber.
     */
    @java.lang.Override
    public int getRelayNumber() {
      return relayNumber_;
    }

    public static final int LATCH_FIELD_NUMBER = 3;
    private boolean latch_;
    /**
     * <code>optional bool latch = 3;</code>
     * @return Whether the latch field is set.
     */
    @java.lang.Override
    public boolean hasLatch() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool latch = 3;</code>
     * @return The latch.
     */
    @java.lang.Override
    public boolean getLatch() {
      return latch_;
    }

    public static final int CHIME_FIELD_NUMBER = 4;
    private boolean chime_;
    /**
     * <code>optional bool chime = 4;</code>
     * @return Whether the chime field is set.
     */
    @java.lang.Override
    public boolean hasChime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool chime = 4;</code>
     * @return The chime.
     */
    @java.lang.Override
    public boolean getChime() {
      return chime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, relayNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, latch_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, chime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, relayNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, latch_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, chime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.spcgreenville.deagan.Proto.DeaganRequest)) {
        return super.equals(obj);
      }
      org.spcgreenville.deagan.Proto.DeaganRequest other = (org.spcgreenville.deagan.Proto.DeaganRequest) obj;

      if (hasHeartbeat() != other.hasHeartbeat()) return false;
      if (hasHeartbeat()) {
        if (getHeartbeat()
            != other.getHeartbeat()) return false;
      }
      if (hasRelayNumber() != other.hasRelayNumber()) return false;
      if (hasRelayNumber()) {
        if (getRelayNumber()
            != other.getRelayNumber()) return false;
      }
      if (hasLatch() != other.hasLatch()) return false;
      if (hasLatch()) {
        if (getLatch()
            != other.getLatch()) return false;
      }
      if (hasChime() != other.hasChime()) return false;
      if (hasChime()) {
        if (getChime()
            != other.getChime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeartbeat()) {
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHeartbeat());
      }
      if (hasRelayNumber()) {
        hash = (37 * hash) + RELAY_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getRelayNumber();
      }
      if (hasLatch()) {
        hash = (37 * hash) + LATCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLatch());
      }
      if (hasChime()) {
        hash = (37 * hash) + CHIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getChime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.spcgreenville.deagan.Proto.DeaganRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.spcgreenville.deagan.DeaganRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.spcgreenville.deagan.DeaganRequest)
        org.spcgreenville.deagan.Proto.DeaganRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.spcgreenville.deagan.Proto.DeaganRequest.class, org.spcgreenville.deagan.Proto.DeaganRequest.Builder.class);
      }

      // Construct using org.spcgreenville.deagan.Proto.DeaganRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        heartbeat_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        relayNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        latch_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        chime_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor;
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganRequest getDefaultInstanceForType() {
        return org.spcgreenville.deagan.Proto.DeaganRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganRequest build() {
        org.spcgreenville.deagan.Proto.DeaganRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganRequest buildPartial() {
        org.spcgreenville.deagan.Proto.DeaganRequest result = new org.spcgreenville.deagan.Proto.DeaganRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.heartbeat_ = heartbeat_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.relayNumber_ = relayNumber_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.latch_ = latch_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.chime_ = chime_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.spcgreenville.deagan.Proto.DeaganRequest) {
          return mergeFrom((org.spcgreenville.deagan.Proto.DeaganRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.spcgreenville.deagan.Proto.DeaganRequest other) {
        if (other == org.spcgreenville.deagan.Proto.DeaganRequest.getDefaultInstance()) return this;
        if (other.hasHeartbeat()) {
          setHeartbeat(other.getHeartbeat());
        }
        if (other.hasRelayNumber()) {
          setRelayNumber(other.getRelayNumber());
        }
        if (other.hasLatch()) {
          setLatch(other.getLatch());
        }
        if (other.hasChime()) {
          setChime(other.getChime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.spcgreenville.deagan.Proto.DeaganRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.spcgreenville.deagan.Proto.DeaganRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean heartbeat_ ;
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return Whether the heartbeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return The heartbeat.
       */
      @java.lang.Override
      public boolean getHeartbeat() {
        return heartbeat_;
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @param value The heartbeat to set.
       * @return This builder for chaining.
       */
      public Builder setHeartbeat(boolean value) {
        bitField0_ |= 0x00000001;
        heartbeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartbeat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heartbeat_ = false;
        onChanged();
        return this;
      }

      private int relayNumber_ ;
      /**
       * <code>optional int32 relay_number = 2;</code>
       * @return Whether the relayNumber field is set.
       */
      @java.lang.Override
      public boolean hasRelayNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 relay_number = 2;</code>
       * @return The relayNumber.
       */
      @java.lang.Override
      public int getRelayNumber() {
        return relayNumber_;
      }
      /**
       * <code>optional int32 relay_number = 2;</code>
       * @param value The relayNumber to set.
       * @return This builder for chaining.
       */
      public Builder setRelayNumber(int value) {
        bitField0_ |= 0x00000002;
        relayNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 relay_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelayNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        relayNumber_ = 0;
        onChanged();
        return this;
      }

      private boolean latch_ ;
      /**
       * <code>optional bool latch = 3;</code>
       * @return Whether the latch field is set.
       */
      @java.lang.Override
      public boolean hasLatch() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bool latch = 3;</code>
       * @return The latch.
       */
      @java.lang.Override
      public boolean getLatch() {
        return latch_;
      }
      /**
       * <code>optional bool latch = 3;</code>
       * @param value The latch to set.
       * @return This builder for chaining.
       */
      public Builder setLatch(boolean value) {
        bitField0_ |= 0x00000004;
        latch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool latch = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatch() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latch_ = false;
        onChanged();
        return this;
      }

      private boolean chime_ ;
      /**
       * <code>optional bool chime = 4;</code>
       * @return Whether the chime field is set.
       */
      @java.lang.Override
      public boolean hasChime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool chime = 4;</code>
       * @return The chime.
       */
      @java.lang.Override
      public boolean getChime() {
        return chime_;
      }
      /**
       * <code>optional bool chime = 4;</code>
       * @param value The chime to set.
       * @return This builder for chaining.
       */
      public Builder setChime(boolean value) {
        bitField0_ |= 0x00000008;
        chime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chime_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.spcgreenville.deagan.DeaganRequest)
    }

    // @@protoc_insertion_point(class_scope:org.spcgreenville.deagan.DeaganRequest)
    private static final org.spcgreenville.deagan.Proto.DeaganRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.spcgreenville.deagan.Proto.DeaganRequest();
    }

    public static org.spcgreenville.deagan.Proto.DeaganRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DeaganRequest>
        PARSER = new com.google.protobuf.AbstractParser<DeaganRequest>() {
      @java.lang.Override
      public DeaganRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeaganRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeaganRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeaganRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.spcgreenville.deagan.Proto.DeaganRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeaganResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.spcgreenville.deagan.DeaganResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return Whether the heartbeat field is set.
     */
    boolean hasHeartbeat();
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return The heartbeat.
     */
    boolean getHeartbeat();

    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return Whether the relayOneStatus field is set.
     */
    boolean hasRelayOneStatus();
    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return The relayOneStatus.
     */
    java.lang.String getRelayOneStatus();
    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return The bytes for relayOneStatus.
     */
    com.google.protobuf.ByteString
        getRelayOneStatusBytes();

    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return Whether the realyTwoStatus field is set.
     */
    boolean hasRealyTwoStatus();
    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return The realyTwoStatus.
     */
    java.lang.String getRealyTwoStatus();
    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return The bytes for realyTwoStatus.
     */
    com.google.protobuf.ByteString
        getRealyTwoStatusBytes();
  }
  /**
   * Protobuf type {@code org.spcgreenville.deagan.DeaganResponse}
   */
  public static final class DeaganResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.spcgreenville.deagan.DeaganResponse)
      DeaganResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeaganResponse.newBuilder() to construct.
    private DeaganResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeaganResponse() {
      relayOneStatus_ = "";
      realyTwoStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeaganResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeaganResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              heartbeat_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              relayOneStatus_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              realyTwoStatus_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.spcgreenville.deagan.Proto.DeaganResponse.class, org.spcgreenville.deagan.Proto.DeaganResponse.Builder.class);
    }

    private int bitField0_;
    public static final int HEARTBEAT_FIELD_NUMBER = 1;
    private boolean heartbeat_;
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool heartbeat = 1;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public boolean getHeartbeat() {
      return heartbeat_;
    }

    public static final int RELAY_ONE_STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object relayOneStatus_;
    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return Whether the relayOneStatus field is set.
     */
    @java.lang.Override
    public boolean hasRelayOneStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return The relayOneStatus.
     */
    @java.lang.Override
    public java.lang.String getRelayOneStatus() {
      java.lang.Object ref = relayOneStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          relayOneStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string relay_one_status = 2;</code>
     * @return The bytes for relayOneStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRelayOneStatusBytes() {
      java.lang.Object ref = relayOneStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relayOneStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REALY_TWO_STATUS_FIELD_NUMBER = 3;
    private volatile java.lang.Object realyTwoStatus_;
    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return Whether the realyTwoStatus field is set.
     */
    @java.lang.Override
    public boolean hasRealyTwoStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return The realyTwoStatus.
     */
    @java.lang.Override
    public java.lang.String getRealyTwoStatus() {
      java.lang.Object ref = realyTwoStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          realyTwoStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string realy_two_status = 3;</code>
     * @return The bytes for realyTwoStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRealyTwoStatusBytes() {
      java.lang.Object ref = realyTwoStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realyTwoStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relayOneStatus_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, realyTwoStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relayOneStatus_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, realyTwoStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.spcgreenville.deagan.Proto.DeaganResponse)) {
        return super.equals(obj);
      }
      org.spcgreenville.deagan.Proto.DeaganResponse other = (org.spcgreenville.deagan.Proto.DeaganResponse) obj;

      if (hasHeartbeat() != other.hasHeartbeat()) return false;
      if (hasHeartbeat()) {
        if (getHeartbeat()
            != other.getHeartbeat()) return false;
      }
      if (hasRelayOneStatus() != other.hasRelayOneStatus()) return false;
      if (hasRelayOneStatus()) {
        if (!getRelayOneStatus()
            .equals(other.getRelayOneStatus())) return false;
      }
      if (hasRealyTwoStatus() != other.hasRealyTwoStatus()) return false;
      if (hasRealyTwoStatus()) {
        if (!getRealyTwoStatus()
            .equals(other.getRealyTwoStatus())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeartbeat()) {
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHeartbeat());
      }
      if (hasRelayOneStatus()) {
        hash = (37 * hash) + RELAY_ONE_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getRelayOneStatus().hashCode();
      }
      if (hasRealyTwoStatus()) {
        hash = (37 * hash) + REALY_TWO_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getRealyTwoStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.spcgreenville.deagan.Proto.DeaganResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.spcgreenville.deagan.Proto.DeaganResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.spcgreenville.deagan.DeaganResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.spcgreenville.deagan.DeaganResponse)
        org.spcgreenville.deagan.Proto.DeaganResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.spcgreenville.deagan.Proto.DeaganResponse.class, org.spcgreenville.deagan.Proto.DeaganResponse.Builder.class);
      }

      // Construct using org.spcgreenville.deagan.Proto.DeaganResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        heartbeat_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        relayOneStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        realyTwoStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.spcgreenville.deagan.Proto.internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor;
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganResponse getDefaultInstanceForType() {
        return org.spcgreenville.deagan.Proto.DeaganResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganResponse build() {
        org.spcgreenville.deagan.Proto.DeaganResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.spcgreenville.deagan.Proto.DeaganResponse buildPartial() {
        org.spcgreenville.deagan.Proto.DeaganResponse result = new org.spcgreenville.deagan.Proto.DeaganResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.heartbeat_ = heartbeat_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.relayOneStatus_ = relayOneStatus_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.realyTwoStatus_ = realyTwoStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.spcgreenville.deagan.Proto.DeaganResponse) {
          return mergeFrom((org.spcgreenville.deagan.Proto.DeaganResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.spcgreenville.deagan.Proto.DeaganResponse other) {
        if (other == org.spcgreenville.deagan.Proto.DeaganResponse.getDefaultInstance()) return this;
        if (other.hasHeartbeat()) {
          setHeartbeat(other.getHeartbeat());
        }
        if (other.hasRelayOneStatus()) {
          bitField0_ |= 0x00000002;
          relayOneStatus_ = other.relayOneStatus_;
          onChanged();
        }
        if (other.hasRealyTwoStatus()) {
          bitField0_ |= 0x00000004;
          realyTwoStatus_ = other.realyTwoStatus_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.spcgreenville.deagan.Proto.DeaganResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.spcgreenville.deagan.Proto.DeaganResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean heartbeat_ ;
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return Whether the heartbeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return The heartbeat.
       */
      @java.lang.Override
      public boolean getHeartbeat() {
        return heartbeat_;
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @param value The heartbeat to set.
       * @return This builder for chaining.
       */
      public Builder setHeartbeat(boolean value) {
        bitField0_ |= 0x00000001;
        heartbeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool heartbeat = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartbeat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heartbeat_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object relayOneStatus_ = "";
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @return Whether the relayOneStatus field is set.
       */
      public boolean hasRelayOneStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @return The relayOneStatus.
       */
      public java.lang.String getRelayOneStatus() {
        java.lang.Object ref = relayOneStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            relayOneStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @return The bytes for relayOneStatus.
       */
      public com.google.protobuf.ByteString
          getRelayOneStatusBytes() {
        java.lang.Object ref = relayOneStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relayOneStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @param value The relayOneStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRelayOneStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        relayOneStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelayOneStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        relayOneStatus_ = getDefaultInstance().getRelayOneStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string relay_one_status = 2;</code>
       * @param value The bytes for relayOneStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRelayOneStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        relayOneStatus_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realyTwoStatus_ = "";
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @return Whether the realyTwoStatus field is set.
       */
      public boolean hasRealyTwoStatus() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @return The realyTwoStatus.
       */
      public java.lang.String getRealyTwoStatus() {
        java.lang.Object ref = realyTwoStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            realyTwoStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @return The bytes for realyTwoStatus.
       */
      public com.google.protobuf.ByteString
          getRealyTwoStatusBytes() {
        java.lang.Object ref = realyTwoStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realyTwoStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @param value The realyTwoStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRealyTwoStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        realyTwoStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealyTwoStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        realyTwoStatus_ = getDefaultInstance().getRealyTwoStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string realy_two_status = 3;</code>
       * @param value The bytes for realyTwoStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRealyTwoStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        realyTwoStatus_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.spcgreenville.deagan.DeaganResponse)
    }

    // @@protoc_insertion_point(class_scope:org.spcgreenville.deagan.DeaganResponse)
    private static final org.spcgreenville.deagan.Proto.DeaganResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.spcgreenville.deagan.Proto.DeaganResponse();
    }

    public static org.spcgreenville.deagan.Proto.DeaganResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DeaganResponse>
        PARSER = new com.google.protobuf.AbstractParser<DeaganResponse>() {
      @java.lang.Override
      public DeaganResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeaganResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeaganResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeaganResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.spcgreenville.deagan.Proto.DeaganResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_spcgreenville_deagan_DeaganRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_spcgreenville_deagan_DeaganResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033src/main/proto/deagan.proto\022\030org.spcgr" +
      "eenville.deagan\"V\n\rDeaganRequest\022\021\n\thear" +
      "tbeat\030\001 \001(\010\022\024\n\014relay_number\030\002 \001(\005\022\r\n\005lat" +
      "ch\030\003 \001(\010\022\r\n\005chime\030\004 \001(\010\"W\n\016DeaganRespons" +
      "e\022\021\n\theartbeat\030\001 \001(\010\022\030\n\020relay_one_status" +
      "\030\002 \001(\t\022\030\n\020realy_two_status\030\003 \001(\tB!\n\030org." +
      "spcgreenville.deaganB\005Proto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_spcgreenville_deagan_DeaganRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_spcgreenville_deagan_DeaganRequest_descriptor,
        new java.lang.String[] { "Heartbeat", "RelayNumber", "Latch", "Chime", });
    internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_spcgreenville_deagan_DeaganResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_spcgreenville_deagan_DeaganResponse_descriptor,
        new java.lang.String[] { "Heartbeat", "RelayOneStatus", "RealyTwoStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
